{{- if and (.Values.karpenter) (.Values.karpenter.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: kube-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/karpenter
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        karpenter:
        {{- toYaml .Values.karpenter | nindent 10 }}
      parameters:
        - name: karpenter.serviceAccount.name
          value: {{ .Values.karpenter.serviceAccountName }}
        - name: karpenter.clusterName
          value: {{ .Values.clusterName }}
        - name: karpenter.clusterEndpoint
          value: {{ .Values.karpenter.controllerClusterEndpoint }}
        - name: karpenter.aws.defaultInstanceProfile
          value: {{ .Values.karpenter.awsDefaultInstanceProfile }}
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-karpenter
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-karpenter
  # property-like keys; each key maps to a simple value
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
{{- end -}}
