# for details on all options
# https://github.com/hashicorp/vault-helm/blob/main/values.yaml
ui:
  enabled: true

volumes:
  - name: plugins
    persistentVolumeClaim:
      claimName: ebs-claim
volumeMounts:
  - mountPath: /etc/vault/vault_plugins
    name: plugins
    readOnly: true
